### ISSUE TITLE
Want a way to customize RV node creation in RV adapter

### ISSUE THREAD

**Issue by jminor** [AcademySoftwareFoundation/OpenTimelineIO#139]
Studios may want to customize the RV node graph (e.g. using custom nodes for dissolves) without forking the whole RV adapter.

We should provide some flexibility in the RV adapter for this, or more generally to allow any adapter to be customized.

**Comment by jminor** [comment]
@avrata @rogernelson @ssteinbach is this issue still relevant now that RV has native OTIO support? More broadly, should we retire the RV adapter entirely?

**Comment by rogernelson** [comment]
Hey sorry for the delayed response, I was using up my last week of parental leave. 

I would say the issue is not relevant anymore:
1) The adapter is native in RV now
2) The adapter shipped with RV supports custom node creation

I think we had some discussion regarding splitting off all the adapters into their own repos to maintained by their owners (us, Autodesk, in the case of this RV adapter). Maybe it's something we can discuss at the next TSC with @eric-desruisseaux-adsk as well.
