### ISSUE TITLE
Example in the README does not work

### ISSUE THREAD

**Issue by palemieux** [AcademySoftwareFoundation/OpenTimelineIO#1554]
The Python example from `README.md` returns an error.

Executing:

```
import opentimelineio as otio

timeline = otio.adapters.read_from_file("foo.aaf")
for clip in timeline.find_clips():
  print(clip.name, clip.duration())
```

returns

`AttributeError: 'opentimelineio._otio.Timeline' object has no attribute 'find_clips'`

**Comment by apetrynet** [comment]
Hi @palemieux!
What version of OTIO are you currently using? The `find_clips()` method was recently added to the "main" branch and is not available in the latest released version 0.15.
For some reason there is no ReadTheDocs for 0.15 :thinking: 

To make your example work, please try: `timeline.each_clip()`. Note that this is deprecated in the upcoming release.

**Comment by palemieux** [comment]
> the find_clips() method was recently added to the "main" branch and is not available in the latest released version 0.15.

Ok. That is likely the issue.

> To make your example work, please try: timeline.each_clip(). Note that this is deprecated in the upcoming release.

Yes, that is what I ended up doing.

> For some reason there is no ReadTheDocs for 0.15 🤔

Ok.

I recommend not breaking the API between major releases.

**Comment by JeanChristopheMorinPerso** [comment]
>I recommend not breaking the API between major releases.

0.15 > 0.16 isn't a major. There is also a notice in the README that says:
>OpenTimelineIO is currently in Public Beta. That means that it may be missing some essential features and there are large changes planned. During this phase we actively encourage you to provide feedback, requests, comments, and/or contributions.

**Comment by jminor** [comment]
Thanks for catching the documentation problem. The ReadTheDocs build for v0.15 has been pushed, so that issue is resolved. 

We will certainly flag this API change when the next release happens, though as you noted, we did not communicate the deprecation in the previous release. Our release cadence has been much slower than we would like, which makes that level of planning difficult. If we want to be strict about it, we could add back shims for the old name, mark them as deprecated, and then remove the shims in the following release.

Also, if you're curious, you can see the reason for the rename here: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1409

**Comment by JeanChristopheMorinPerso** [comment]
@jminor they were correctly marked as deprecated, see https://opentimelineio.readthedocs.io/en/stable/api/python/opentimelineio.core.html#opentimelineio.core.Track.each_clip. Though, it is true we didn't publicize it loudly.

**Comment by JeanChristopheMorinPerso** [comment]
Well, I say "correctly". It is correct from my point of view. A better word would be "formally". So we did some effort to announce it in some way, but more communication would have been better.

**Comment by jminor** [comment]
Ah thanks. I only looked at the release notes and didn't see it mentioned. We can discuss before the next release.
